force-app/main/default/objects/Consultant__c/Consultant__c.object-meta.xml
<CustomObject>
    <label>Consultant</label>
    <nameField>
        <displayFormat>CID{000}</displayFormat>
        <label>Consultant ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Consultants</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Consultant__c/fields/Pan_Number__c.field-meta.xml
<CustomField>
    <fullName>Pan_Number__c</fullName>
    <label>Pan Number</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/Consultant_Class.cls
public class Consultant_Class {
    public static void afterInsert(List<Consultant__c> con){
        List<String> li=new List<String>();
        for(Consultant__c c: con){
           li.add(c.Pan_Number__c);
        }
        integer count=[select count() from Consultant__c where Pan_Number__c IN : li];
        if(count>0){
            ApexPages.Message msg=new ApexPages.Message(ApexPages.Severity.ERROR,'Duplicates Not Allowed');
            ApexPages.addMessage(msg);
        }else{
            insert con;
        }
    }
}