force-app/main/default/objects/Retail_Store__c/Retail_Store__c.object-meta.xml
<CustomObject>
    <label>Retail Store</label>
    <nameField>
        <label>Store Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Retail Store</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Retail_Store__c/fields/Days_Since_Opening__c.field-meta.xml
<CustomField>
    <fullName>Days_Since_Opening__c</fullName>
    <label>Days Since Opening</label>
    <precision>6</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/DaysSinceOpening.cls
public class DaysSinceOpening {  //trigger Handler
    Public static void insertOrUpdate(List<Retail_Store__c> insertOrUpdateList){ // passing list of records 
        //iterating over the list
        for(Retail_Store__c c: insertOrUpdateList){  
            //Calculating days from Opening date to till date and assigning the value to variable called daysSinceOpening
            integer daysSinceOpening=c.Opening_Date__c.daysBetween(Date.TODAY());
            //Updating the new field called Days_Since_Opening__c whith the daysSinceOpening value
			c.Days_Since_Opening__c=daysSinceOpening;
        }
    }
}