force-app/main/default/objects/OppServices__c/OppServices__c.object-meta.xml
<CustomObject>
    <label>OppServices</label>
    <nameField>
        <displayFormat>S-{0000}</displayFormat>
        <label>OppServices Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>OppServices</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/OppServices__c/fields/App__c.field-meta.xml
<CustomField>
    <fullName>App__c</fullName>
    <label>App</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Oracle</fullName>
            </value>
            <value>
                <fullName>Selenium</fullName>
            </value>
            <value>
                <fullName>Asset Health Insight</fullName>
            </value>
            <value>
                <fullName>Appium</fullName>
            </value>
            <value>
                <fullName>Dot Net</fullName>
            </value>
            <value>
                <fullName>Java</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/OppServices__c/fields/OppTrack__c.field-meta.xml
<CustomField>
    <fullName>OppTrack__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity Track</label>
    <referenceTo>Opportunity_Track__c</referenceTo>
    <relationshipLabel>OppServices</relationshipLabel>
    <relationshipName>OppServices</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/Poc_dashboard.cls
public class Poc_dashboard {

  @AuraEnabled(cacheable=true)
  public static List<Integer> technologies(){
    List<Integer> intList=new List<Integer>();
    integer a=0;
    integer b=0;
    integer c=0;
    integer d=0;
    integer e=0;
    integer f=0;
    List<OppServices__c> listServices= [select id,App__c,Technologies__c,OppTrack__c from OppServices__c WHERE OppTrack__c!=null];
    for(OppServices__c v:listServices){
        String nm=v.Technologies__c;
        
       if (nm.contains('Oracle')){
        a+=1;
       }else if(nm.contains('Selenium')){
        b+=1;
       }else if(nm.contains('Asset Health Insight')){
        c+=1;
       }else if(nm.contains('Appium')){
        d+=1;
       }else if(nm.contains('Dot Net')){
        e+=1;
       }else{
        f+=1;
       }
    }
    intList.add(a);
    intList.add(b);
    intList.add(c);
    intList.add(d);
    intList.add(e);
    intList.add(f);
    return intList;
  }


}