force-app/main/default/objects/Opportunity_Track__c/Opportunity_Track__c.object-meta.xml
<CustomObject>
    <label>Opportunity Track</label>
    <nameField>
        <label>Customer</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Opportunity Track</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/OppServices__c/OppServices__c.object-meta.xml
<CustomObject>
    <label>OppServices</label>
    <nameField>
        <displayFormat>S-{0000}</displayFormat>
        <label>OppServices Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>OppServices</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/OppServices__c/fields/App__c.field-meta.xml
<CustomField>
    <fullName>App__c</fullName>
    <label>App</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Oracle</fullName>
            </value>
            <value>
                <fullName>Selenium</fullName>
            </value>
            <value>
                <fullName>Asset Health Insight</fullName>
            </value>
            <value>
                <fullName>Appium</fullName>
            </value>
            <value>
                <fullName>Dot Net</fullName>
            </value>
            <value>
                <fullName>Java</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/OppServices__c/fields/OppTrack__c.field-meta.xml
<CustomField>
    <fullName>OppTrack__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity Track</label>
    <referenceTo>Opportunity_Track__c</referenceTo>
    <relationshipLabel>OppServices</relationshipLabel>
    <relationshipName>OppServices</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/OppTrackingClass.cls
public class OppTrackingClass {
    public List<OppServices__c> opp {set;get;}
  //  public List<OppServices__c> oppList {set;get;}
    public boolean flag {get;set;}
    public Opportunity_Track__c o {set;get;}
    public OppTrackingClass(){ 
        opp=new List<OppServices__c>();
      //  oppList=new List<OppServices__c>();
        o=new Opportunity_Track__c();
        callMe();
        flag=false;
    }
    public void callMe(){
        flag=true;
        OppServices__c os=new OppServices__c();
        opp.add(os);
       
    }
    public PageReference invoke(){
        insert o;
        for(OppServices__c v: opp){
            v.OppTrack__c=o.Id;
        }
        insert opp;
        PageReference p=new PageReference('/'+o.Id);
        return p;
        
    }
    public void change(){
        for(OppServices__c s: opp){
            if(s.App__c=='Java'){
                s.Technologies__c='IIoT';
                 opp.add(s);
            }
        }
       
    }
}