force-app/main/default/objects/order__c/order__c.object-meta.xml
<CustomObject>
    <label>order</label>
    <nameField>
        <label>Contact Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>orders</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/order__c/fields/Payment_Mode__c.field-meta.xml
<CustomField>
    <fullName>Payment_Mode__c</fullName>
    <label>Payment Mode</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Cash</fullName>
            </value>
            <value>
                <fullName>Loan</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/product__c/product__c.object-meta.xml
<CustomObject>
    <label>product</label>
    <nameField>
        <label>Product Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>products</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/Payment_Mode.cls
public class Payment_Mode {
  /*  public static void call(List<Order__c> li){
        List<Order__c> cash=new List<Order__c>();
        List<Order__c> loan=new List<Order__c>();
        
        for(Order__c c: li){
            if(c.Payment_Mode__c == 'Cash'){
                cash.add(c);
            }
            else{
                loan.add(c);
            }
        }
        Integer c=cash.size();
        Integer l=loan.size();
        Product__c p=[select id,Name from Product__c];
        p.By_Cash__c=c;
        p.By_Loan__c=l;
    }
*/
}